### ISSUE TITLE
Move com.vaadin.server.data classes to com.vaadin.data

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework8-issues#245] opened 2016-09-13 09:24 UTC
Data classes are not related to the server (servlet/service) in any way

**Comment by jdahlstrom** [comment] 2016-09-14 14:57
c.v.server.data classes are related to server-side data communication. c.v.data is for ~pure data model stuff.

 c.v.server is a huge mess currently with no coherent theme except "this happens on server". There are lots of high-level UI/comms stuff like extensions and connectors that don't have anything to do with servlet/service either. Also, FontAwesome.

**Comment by pleku** [comment] 2016-10-11 10:16
@Legioth please clarify is this part of the "new DoDo" and add or close.

**Comment by Legioth** [comment] 2016-10-11 12:37
Duplicate of #110

**Closed as completed by Legioth** 2016-10-11 12:37 UTC
Labels: Project packaging build release
