### ISSUE TITLE
AL doesn't show required indicator

### ISSUE THREAD

**Issue by anssit** [vaadin/framework8-issues#459] opened 2016-11-09 13:16 UTC
Vaadin Designer shows RequiredIndicatorVisible property in its property editor for all components that implement HasValue<T> interface. However, toggling its value has no effect on the appearance of CheckBoxGroup, RadioButtonGroup, ColorPicker or ColorPickerArea. 

Update:
AL uses absolute positions for its children. By default the position is (0,0) which makes component caption invisible (out of the AL area). This is true for mentioned CheckBoxGroup, RadioButtonGroup.

The issue with  ColorPicker  and ColorPickerArea is different and will be extracted.

**Comment by denis-anisimov** [comment] 2016-11-25 06:48
Cannot reproduce the bug with CheckBoxGroup, RadioButtonGroup (at least with VerticalLayout).
Might be an issue with layout as well. Please check which layout you use and report here if the issue is still reproducible.

The bug with ColorPicker or ColorPickerArea is genuine. I'm able to reproduce it.

**Comment by denis-anisimov** [comment] 2016-11-25 07:41
This is not a bug.
This is a new feature.
As I said: I don't see any reasons why CheckBoxGroup, RadioButtonGroup doesn't work (unless there have been recent changes).
ColorPicker or ColorPickerArea never had "required" property working. In old version it's not handled properly and new version has no changes in that regard.
So this is absolutely new feature request.

**Comment by anssit** [comment] 2016-11-25 09:02
It seems to work inside FormLayout for CheckBox/RadioButtonGroup. It also seems to work with VerticalLayout for those components. Maybe I tested it with AbsoluteLayout because there the indicator can easily be cropped out of sight if it's next to upper edge of the layout.

Found another component that it does not work for in Vertical/FormLayout: CheckBox.

I updated the description accordingly.

**Comment by denis-anisimov** [comment] 2016-11-25 09:10
I would prefer to distinguish components: each component should have it's own bug.
As now : CheckBoxGroup, RadioButtonGroup should work and there is perhaps a bug with some layouts.
ColorPicker or ColorPickerArea have never worked and this is just a new feature (technically, though contract says that they should work, here you are right).

Let's keep this specific issue for CheckBox/RadioButtonGroup.

I need exact layouts where it doesn't work here. Written down explicitly.

ColorPicker and ColorPickerArea (can be together) should be extracted to the separate ticket. Please mention that this doesn't work in ANY layout.

CheckBox should be extracted to the separate ticket. All layouts where it doesn't work should be mentioned (or ALL).

It's much easier to track the issue and work on it in this way.

**Comment by denis-anisimov** [comment] 2016-11-25 10:35
As I said the issue with CheckBox/RadioButtonGroup (and most likely with CheckBox, any field) is layout specific issue.
Absolute layout shows its caption (the whole caption , not just indicator) out of its area.
So caption becomes invisible.
This is AboluteLayout issue only.

ColorPicker and ColorPickerArea are totally different cases.

**Comment by denis-anisimov** [comment] 2016-11-25 10:57
Oh my gosh........
It's again logical problem with API.
AbsoluteLayout is supposed to be used with component position. So each time when a component is added to AbsoluteLayout it should be positioned somehow in the layout.

By default (0,0) position is used. This position just doesn't allow Required indicator to become visible because it has to be on the top of the component.

From the one point of view component should be positioned in a way that allows to see its indicator. But this contradicts with component position because caption is not a part of the component.

So if component position is (0,0) (be default) then caption position will be negative and it becomes invisible. If AL changes the component position to make caption visible then component position is not anymore (0,0). But it has to be.

This is a consequence of bad Caption feature design . And I can't do anything here.

This issue which is about AbsoluteLayout only (as I said ColorPicker and ColorPickerArea should be extracted) is invalid. I'm closing it as WONTFIX.

Designer has to position components in AL so that their positions allow to see their captions (if any). Sorry, I know this is ugly but current design doesn't allow to do anything else.

I will add tests for required indicator and layouts as a part of the issue since I already have them.
But nothing will be done to fix the issue.

**Comment by anssit** [comment] 2016-11-25 11:03
Man you're quick!

For CheckBoxGroup I did a bit more testing and figured its requiredIndicatorVisible is not working in Panel, VerticalSplitPanel and HorizontalPanel either. Though if you wrap the component with another layout inside said Panel it will work.

I'll create separate issues for CheckBox and ColorPickers and fill them with details.

**Comment by denis-anisimov** [comment] 2016-11-25 11:12
Arghh......
Panel, VerticalSplitPanel and HorizontalPanel are not layouts.

And again: this is bad Caption feature design. 
Caption is supposed to work (required indicator is a part of caption) with layouts.
(or there are components that handles their caption by themselves , like Button).

I know, this is a bug.

But again: this is what we have unfortunately. Because of caption design.

The workaround: set some layout as a content into Panel and as a left/side (bottom/top) panels in HSP/VSP. This is the usual way to use them actually. But it's not an excuse of course.

So: I would like to have separate issues for Panel, VerticalSplitPanel and HorizontalPanel (can be one issue since it's already localized). They are not layouts and should be extracted from here.

Again: sorry for that. But we should live with bad design decisions made a long time ago.
Most likely it won't be fixed at all since there will no such issue in FW9 and it's too hard to rewrite it for FW8.

**Comment by anssit** [comment] 2016-11-25 11:25
There appears to be no problem with Radio/CheckBoxGroups in any of the layouts. It works also in AbsoluteLayout (besides being completely cropped if the group is located at (x,0)).

What if I edit this bug to be about those groups used in the context of the different Panels?

You can then prioritize the bug as you wish. I do not think there's any pressure from Designer's point of view to get this fixed. Just good to know the situation and workarounds with all the components.

**Comment by denis-anisimov** [comment] 2016-11-25 11:26
One more ticket for ComboBox please.

It's similar to ColorPicker and ColorPickerArea: it never have worked for ComboBox. Because it handles caption by itself (doesn't delegate to layout). But it's kind of useless to have required for ComboBox.

**Comment by denis-anisimov** [comment] 2016-11-25 11:31
>There appears to be no problem with Radio/CheckBoxGroups in .....

This is complex issue with many different components/layouts.
We need to be able to track it in a proper way.

I have tests for CheckBoxGroup/RadioButtonGroup and all layouts. I will commit them as a part of this ticket.
Let's keep this specific ticket about these components only (and AL where their behavior is 
weird). It will help us to understand what's going on.

Then please extract:
- ColorPicker and ColorPickerArea as a separate issue.
- CheckBox as a separate issue
- Panel, VerticalSplitPanel and HorizontalPanel  as a separate issue (won't be fixed most likely at all , but we need this to be able to track).

**Comment by anssit** [comment] 2016-11-25 11:37
Ok, Denis, please modify this ticket's title and scope to your liking. I'll create the new tickets.

**Comment by denis-anisimov** [comment] 2016-11-25 11:40
https://dev.vaadin.com/review/#/c/14816/

OK

**Comment by anssit** [comment] 2016-11-25 12:00
Created issues:
https://github.com/vaadin/framework8-issues/issues/504 for ColorPickers
https://github.com/vaadin/framework8-issues/issues/505 for CheckBox
https://github.com/vaadin/framework8-issues/issues/506 for Panels

**Comment by denis-anisimov** [comment] 2016-11-25 12:04
OK, very good.
Thanks a lot !

**Comment by anssit** [comment] 2016-11-25 12:09
No problem - my pleasure ;) By the way, "One more ticket for ComboBox please."  -> ComboBox required indicator appears to work just fine in layouts.

**Comment by denis-anisimov** [comment] 2016-11-25 12:20
>No problem - my pleasure ;) By the way, "One more ticket for ComboBox please." -> ComboBox  required indicator appears to work just fine in layouts.

Sorry, I meant CheckBox. For some reason I always mix up CheckBox and ComboBox.

**Closed as completed** 2016-11-25 13:22 UTC
Labels: Forms and field components
