### ISSUE TITLE
Grid header/footer declarative support

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework8-issues#311] opened 2016-09-20 13:25 UTC

**Comment by Artur-** [comment] 2016-09-27 06:51
What does this mean?

**Comment by jdahlstrom** [comment] 2016-09-28 22:20
It means that Grid should read/write header and footer configuration from/to a design like in 7.

**Comment by pleku** [comment] 2016-10-19 12:37
Subtask of #390 ?

**Comment by pleku** [comment] 2016-10-24 07:53
Duplicate of #390

**Closed as completed by pleku** 2016-10-24 07:53 UTC
Labels: Data sources and listing components, BLOCKED, needs design
